/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

import minesweeper.View.GameGUI;

public class App {


    public static void main(String[] args) {
        GameGUI gameGUI = new GameGUI();
        gameGUI.run();
    }
}
